### PR TITLE
FP3

### PR DESCRIPTION
**Pull request by hassan2x**
[fp3.zip](https://github.com/sjasthi/mapper/files/8943496/fp3.zip)

### CODE REVIEW

**Comment by hassan2x** [comment]
.

**Comment by hassan2x** [comment]
.

**Comment by stfranson** [comment]
Cool

**Comment by stfranson** [comment]
Good to go!

**Comment by stfranson** [comment]
Good!

**Review by stfranson — COMMENTED** [review]
test

**Comment by stfranson** [comment]
New data!!!!

**Pull request merged**
